version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: vet_project # Set your desired PostgreSQL database name
      POSTGRES_USER: postgres # Set your desired PostgreSQL username
      POSTGRES_PASSWORD: root # Set your desired PostgreSQL password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
