version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  nginx:
    build:
      context: .
      dockerfile: DockerFile.nginx
    ports:
      - "80:80"
    depends_on:
      - php
