# Use the official PHP image as base
FROM php:8.2.12-cli

# Install system dependencies
RUN apt-get update -y && apt-get install -y nginx libmcrypt-dev libonig-dev unzip zlib1g-dev libzip-dev

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set Composer environment variables
ENV COMPOSER_ALLOW_SUPERUSER 1

# Set working directory
WORKDIR /app

# Copy files from current directory to working directory
COPY . /app

COPY conf/nginx/nginx-site.conf /etc/nginx/sites-available/default
RUN ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default




# Install PHP dependencies
RUN composer install

# Link storage
RUN php artisan storage:link

# Expose port 8001
EXPOSE 8001

# Start Nginx and PHP
CMD service nginx start && php artisan serve --host=0.0.0.0 --port=8001
